"""initial schema

Revision ID: 2daf41bbd4b0
Revises: 
Create Date: 2026-01-23 10:56:49.830534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2daf41bbd4b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('image_url', sa.String(length=256), nullable=True),
    sa.Column('notifications', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename_original', sa.String(length=256), nullable=False),
    sa.Column('filename_stored', sa.String(length=256), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=64), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('sha1', sa.String(length=40), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('sha1', sa.String(length=40), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('yara_result', sa.Text(), nullable=True),
    sa.Column('antivirus_result', sa.Text(), nullable=True),
    sa.Column('virustotal_result', sa.Text(), nullable=True),
    sa.Column('macro_detected', sa.String(length=16), nullable=True),
    sa.Column('stego_detected', sa.String(length=16), nullable=True),
    sa.Column('audio_analysis', sa.Text(), nullable=True),
    sa.Column('sandbox_score', sa.Float(), nullable=True),
    sa.Column('final_verdict', sa.String(length=16), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('engine_version', sa.String(length=64), nullable=True),
    sa.Column('ruleset_version', sa.String(length=64), nullable=True),
    sa.Column('additional_results', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert')
    op.drop_table('analysis')
    op.drop_table('log')
    op.drop_table('file')
    op.drop_table('user')
    # ### end Alembic commands ###
