import os
import re
from pathlib import Path

from locust import HttpUser, task, between


BASE_DIR = Path(__file__).resolve().parent.parent
SAMPLES_DIR = BASE_DIR / "samples"

DEFAULT_USERNAME = os.getenv("FA_LOADTEST_USERNAME", "admin")
DEFAULT_PASSWORD = os.getenv("FA_LOADTEST_PASSWORD", "admin123")
DEFAULT_SAMPLE_NAME = os.getenv(
    "FA_LOADTEST_SAMPLE", "This is a malicious document.docm"
)
SAMPLE_PATH = SAMPLES_DIR / DEFAULT_SAMPLE_NAME


class ForenAlyzeUser(HttpUser):
    """Simulated user that logs in and uploads files.

    This scenario exercises the authenticated flow:
    - GET /auth/login (fetch CSRF token)
    - POST /auth/login (establish session)
    - GET /upload (fetch CSRF token)
    - POST /upload with a sample file
    """

    wait_time = between(1, 5)

    def on_start(self):
        """Log in once at the beginning of the user session."""
        self.client.headers.update({"User-Agent": "ForenAlyzeLoadTest/1.0"})
        self._login()

    def _extract_csrf(self, html: str) -> str:
        """Extract Flask-WTF CSRF token from a rendered form.

        Looks for an input named "csrf_token" and returns its value.
        """

        # Most common pattern generated by Flask-WTF
        match = re.search(r'name="csrf_token"[^>]*value="([^"]+)"', html)
        if match:
            return match.group(1)
        raise ValueError("CSRF token not found in HTML page")

    def _login(self):
        # 1) Load login page to obtain CSRF token
        with self.client.get("/auth/login", name="/auth/login[GET]", catch_response=True) as resp:
            if resp.status_code != 200:
                resp.failure(f"Failed to load login page ({resp.status_code})")
                return
            try:
                csrf_token = self._extract_csrf(resp.text)
            except ValueError as exc:
                resp.failure(str(exc))
                return

        # 2) Submit login form
        form_data = {
            "username": DEFAULT_USERNAME,
            "password": DEFAULT_PASSWORD,
            "csrf_token": csrf_token,
        }
        with self.client.post(
            "/auth/login",
            data=form_data,
            name="/auth/login[POST]",
            catch_response=True,
            allow_redirects=False,
        ) as resp:
            if resp.status_code not in (302, 303):
                resp.failure(f"Login failed ({resp.status_code})")
            else:
                resp.success()

    @task(3)
    def upload_sample_file(self):
        """Upload a sample file and trigger full analysis."""

        # Ensure the sample exists on the Locust machine
        if not SAMPLE_PATH.is_file():
            # Mark this request as failed once, then return quickly
            # to avoid spamming errors.
            self.environment.events.request.fire(
                request_type="FILE",
                name="sample_not_found",
                response_time=0,
                response_length=0,
                exception=FileNotFoundError(f"Sample not found: {SAMPLE_PATH}"),
            )
            return

        # 1) Load upload page (GET /upload) to obtain CSRF token
        with self.client.get("/upload", name="/upload[GET]", catch_response=True) as resp:
            if resp.status_code != 200:
                resp.failure(f"Failed to load upload page ({resp.status_code})")
                return
            try:
                csrf_token = self._extract_csrf(resp.text)
            except ValueError as exc:
                resp.failure(str(exc))
                return

        # 2) POST file with CSRF token
        with SAMPLE_PATH.open("rb") as f:
            files = {"file": (SAMPLE_PATH.name, f, "application/octet-stream")}
            data = {"csrf_token": csrf_token}
            with self.client.post(
                "/upload",
                files=files,
                data=data,
                name="/upload[POST]",
                catch_response=True,
                allow_redirects=False,
            ) as resp:
                if resp.status_code not in (302, 303):
                    resp.failure(f"Upload failed ({resp.status_code})")
                else:
                    resp.success()

    @task(1)
    def browse_dashboard(self):
        """Lightweight navigation to simulate users checking results."""

        self.client.get("/dashboard", name="/dashboard")
        self.client.get("/files", name="/files")
